### ISSUE TITLE
Update to 0.17

### ISSUE THREAD

**Issue by sebbi08** [Bilka2/ChangeMapSettings#1]
Could you update this mod to 0.17 ?

**Comment by Bilka2** [comment]
When I have the time, yes.

**Comment by Bilka2** [comment]
The mod has been updated as much as possible. The API for the map gen settings is missing a lot of features and also returns some bogus values in 0.17. Further notes on the bogus values can be found in the readme/the mod itself/the mod page: https://mods.factorio.com/mod/ChangeMapSettings.
