### ISSUE TITLE
Changing from cheap to expensive prices possible?

### ISSUE THREAD

**Issue by paul23-git** [Bilka2/ChangeMapSettings#10]
Well as per title, I can't seem to find the configuration to change to expensive prices for crafting/science...

**Comment by Bilka2** [comment]
> [difficulty settings] can be modified mid-game. This is however not recommended as different difficulties can have differing technology and recipe trees, which can cause problems for players.

The API doc recommends against allowing to change the difficulty and my mod follows that recommendation.

If you really want to change it, the vanilla map editor (`/editor`) offers the option to change the difficulty settings under the surface tab -> Edit map gen settings -> Advanced tab.
