### ISSUE TITLE
Resources decrease after mod removal

### ISSUE THREAD

**Issue by StarkITA** [Bilka2/ChangeMapSettings#2]
Hi,

if you make changes with the mod, save and remove it from the loaded mods, ALL ore deposits are MUCH smaller, even the ones already generated.

**Comment by Bilka2** [comment]
Please provide a mod list.

**Comment by StarkITA** [comment]
actual-craft-times-remade_1.0.5.zip
Aircraft_1.7.1.zip
alien-biomes_0.5.2.zip
ArmouredBiters_0.18.2.zip
deadlock-beltboxes-loaders_2.3.5.zip
even-distribution_0.3.17.zip
Flow Control_3.0.6.zip
FluidMustFlow_1.2.4.zip
FNEI_0.3.0.zip
helmod_0.10.15.zip
Krastorio2_0.9.11.zip
LightedPolesPlus_1.5.5.zip
LogisticTrainNetwork_1.13.1.zip
LTN_Combinator_0.6.1.zip
manual-inventory-sort_2.2.1.zip
mod-list.json
mod-settings.dat
ModuleInserter_5.0.3.zip
Nanobots_3.2.6.zip
OpteraLib_0.2.1.zip
power-grid-comb_0.18.1.zip
railloader_1.0.0.zip
robot_attrition_0.4.2.zip
Shortcuts_0.7.4.zip
space-exploration-graphics_0.2.1.zip
space-exploration-postprocess_0.2.4.zip
space-exploration_0.2.16.zip
stdlib_1.4.2.zip
StorageTank2_0.5.0.zip
Todo-List_18.0.1.zip
VehicleSnap_1.18.1.zip
WireShortcuts_0.4.1.zip

**Comment by Bilka2** [comment]
> space-exploration_0.2.16.zip

Space exploration changes ore generation, see [the mod page](https://mods.factorio.com/mod/space-exploration):

> The planet you start on, Nauvis, is huge but ultimately limited. It also has limited surface resources (100% size and richness)

So, the behavior you observe is Space Exploration enforcing these limited surface resources. As such, this is intended behaviour by SE and not related to my mod.

**Comment by StarkITA** [comment]
Thanks for the prompt reply!

Keep up the good work :D
