### ISSUE TITLE
Removal of Creative Mod's menu

### ISSUE THREAD

**Issue by dabalciunas** [Bilka2/ChangeMapSettings#7]
When removing the Change Map Settings mod from a game, it removes its button from the top left of the game screen, and this is OK.

However, Creative Mod also places a button at the same spot. When Change Map Settings is removed from the game, it inadvertently also removes Creative Mod's button, which is terribly wrong.

This is causes a big issue, because the only way to restore Creative Mod's button is by removing it and adding it again to the game, which implies on removing all Creative Mod stuff from the game, which is a no-go. So while this is not fixed, one must decide either not having both mods installed, or to never remove Change Map Settings Mod from its game, otherwise Creative Mod will be permanently damaged.

As an additional idea, I would suggest adding an option for showing/hiding the Change Map Settings button, since it is not frequently used in game. This would be an elegant solution for reducing unused UI elements from the game view. This is important because game debug messages are obstructed by this button.

**Comment by Bilka2** [comment]
Can you link the creative mod you're using, please.

**Comment by dabalciunas** [comment]
Creative Mod is widely used for testing Factorio designs:
[Link to Creative Mod](https://mods.factorio.com/mod/creative-mod)

**Comment by Bilka2** [comment]
I wanted to be sure I was using the right mod. I cannot reproduce the issue:

https://user-images.githubusercontent.com/27060268/127767602-e9a5dce3-4e93-4eeb-8187-e2e946018ae4.mp4

Removing the mod is the intended way to hide the button. If this does not conform your expectations, the base game map editor may work better for you. To edit map settings with the map editor, use `/editor` in the console -> surface tab -> edit map gen settings -> change values -> confirm -> `/editor` in console to toggle map editor again.
